# Generated by Django 6.0.7 on 2026-07-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Full name')),
                ('account_name', models.CharField(db_index=True, max_length=120, verbose_name='Account name / handle')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=60, verbose_name='Phone')),
                ('product_category', models.CharField(choices=[('Lens', 'Lens'), ('Flash', 'Flash'), ('Monitor', 'Monitor')], max_length=20, verbose_name='Product category')),
                ('country', models.CharField(max_length=100, verbose_name='Country / region')),
                ('country_other', models.CharField(blank=True, max_length=120, verbose_name='Other country / region')),
                ('state_province', models.CharField(blank=True, max_length=120, verbose_name='State / province')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('postal_code', models.CharField(max_length=40, verbose_name='Postal code')),
                ('full_shipping_address', models.TextField(verbose_name='Full shipping address')),
                ('camera_version', models.CharField(choices=[('Sony', 'Sony'), ('Canon', 'Canon'), ('Fujifilm', 'Fujifilm'), ('Nikon', 'Nikon'), ('Other', 'Other')], max_length=40, verbose_name='Camera version')),
                ('camera_version_other', models.CharField(blank=True, max_length=120, verbose_name='Other camera version')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('gls_confirm', models.BooleanField(default=False, verbose_name='GLS delivery confirmed')),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Tracking number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Shipping information',
                'verbose_name_plural': 'Shipping information',
                'ordering': ['-created_at'],
            },
        ),
    ]
