# Generated by Django 6.0.7 on 2026-07-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginformation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shippinginformation',
            name='product_category',
        ),
    ]
