# Generated by Django 6.0.7 on 2026-07-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_shippinginformation_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippinginformation',
            options={'ordering': ['-created_at'], 'verbose_name': '红人样品申请', 'verbose_name_plural': '红人样品申请'},
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='account_name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='账号名称'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='camera_version',
            field=models.CharField(choices=[('Sony', 'Sony'), ('Canon', 'Canon'), ('Fujifilm', 'Fujifilm'), ('Nikon', 'Nikon'), ('Other', 'Other')], max_length=40, verbose_name='相机版本'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='camera_version_other',
            field=models.CharField(blank=True, max_length=120, verbose_name='其他相机版本'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='city',
            field=models.CharField(max_length=120, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='country',
            field=models.CharField(max_length=100, verbose_name='国家/地区'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='country_other',
            field=models.CharField(blank=True, max_length=120, verbose_name='其他国家/地区'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='full_shipping_address',
            field=models.TextField(verbose_name='完整收货地址'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='gls_confirm',
            field=models.BooleanField(default=False, verbose_name='已确认 GLS 可派送'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='phone',
            field=models.CharField(max_length=60, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='postal_code',
            field=models.CharField(max_length=40, verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='state_province',
            field=models.CharField(blank=True, max_length=120, verbose_name='州/省'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='物流单号'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
